name = "Clear Skies"
author = "Khazoda"
version = "1.3.19"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "276bcd1270ff637e277be3a392cd5b4a54f707ae81bc87c97a688fa23df10922"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21-rc1", "1.21", "1.21.1"]
datapack-folder = "basicweapons_materialpacks/"
no-internal-hashes = ["global_packs/required_resources/*"]
